version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  python:
    build: .
    container_name: etl
    volumes:
      - ./etl:/app
      - ./data:/data
    depends_on:
      - mongo
    env_file:
      - .env
    command: ["python", "/app/etl.py"]

volumes:
  mongodb_data: